### ISSUE TITLE
Confirm dialog could have more than 2 options

### ISSUE THREAD

**Issue by hamed-musallam** [zakodium-oss/react-science#639] opened 2024-01-29 13:27 UTC
<img width="507" alt="Screenshot 2024-01-29 at 14 27 24" src="https://github.com/zakodium-oss/react-science/assets/35760236/c2feaaa1-8483-4582-bc51-61fff57b8ee1">

**Comment by targos** [comment] 2024-01-29 13:36
This is a duplicate of https://github.com/zakodium-oss/react-science/issues/525

**Closed as not planned** 2024-04-03 12:12 UTC
