### ISSUE TITLE
Ability to nest `Toolbar.Item` as an opening button for a `DropdownMenu`

### ISSUE THREAD

**Issue by Xstoudi** [zakodium-oss/react-science#515] opened 2023-07-01 14:14 UTC
This example:

```tsx
    <DropdownMenu
      trigger="click"
      onSelect={selectOption}
      options={filterOptions}
    >
      <Toolbar.Item title="Filters">
        <FaFilter />
      </Toolbar.Item>
    </DropdownMenu>
```

leads to having two `button` tag nested, which trigger the following warning:
```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
```

**Comment by targos** [comment] 2023-07-03 09:31
Do you have a suggestion to fix it?

**Comment by targos** [comment] 2023-07-07 05:59
Conceptually, you want the dropdown's trigger to be your toolbar item. I think we need to change the API to accept that. In other words, an option to render your own trigger button.

**Comment by stropitek** [comment] 2023-12-15 14:46
@targos duplicate of https://github.com/zakodium-oss/react-science/issues/612?

**Comment by targos** [comment] 2023-12-15 14:57
Seems like it.

**Closed** 2024-02-20 07:40 UTC
